### ISSUE TITLE
Parse commit from stdin

### ISSUE THREAD

**Issue by dpc** [crywolf/mkchlog#15]
A natural place to check a commit message would be in a git `commit-msg` hook. But for this to be easy to implement it needs to be possible to check it before it's actually commited, ideally passed as text via stdin.

For reference here is a [similar issue I opened before in `convco` - similar tool for Conventional Commits](https://github.com/convco/convco/issues/100). [The git hook in Fedimint repo using it](https://github.com/fedimint/fedimint/blob/8166fa709445afee94279f106ee3e51668d7a0ba/misc/git-hooks/commit-msg#L19).

**Comment by crywolf** [comment]
This feature was implemented by ac0df22c6b5c9e4ec387b61b7997d420a1b6d36c
In `.githooks` directory is the `commit-msg` file I am currently using.

Thanks @dpc ! I enjoyed recent Citadel Dispatch about NIX with you, Nifty and Kody. Cool stuff!

**Comment by dpc** [comment]
Thanks!
