### ISSUE TITLE
Allow putting commit ID to global configuration

### ISSUE THREAD

**Issue by Kixunil** [crywolf/mkchlog#2]
Currently the commit needs to be specified on command line every time which is very annoying - not only writing but also checking which was it. This is also duplicated between CI and local CLI.

Instead it should be possible to set it in yaml.

Proposed interface:

```yml
skip-commits-up-to: COMMIT_HERE
```

When `-c` is not specified and `skip_commits_before` is it works as if the value was passed to `-c`. When both are specified the argument is used.

**Comment by crywolf** [comment]
Sure, will add that :+1:

**Comment by crywolf** [comment]
Thanks! Solved by d995303fe7f11652583cf36e32a080d6baff11ad
