### ISSUE TITLE
Bug: Empty section still displayed

### ISSUE THREAD

**Issue by Kixunil** [crywolf/mkchlog#4]
Using current `mkchlog.yml` `mkchlog gen` outputs security section even when there are no security commits.

**Comment by crywolf** [comment]
True, I found that yesterday as well. Will fix it. Finally we have some real commits to test on them :)

**Comment by crywolf** [comment]
Solved by e1c0a2b5edefb49f51ebe34fa1ef1f8e9bacfcbd
